name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    types: [opened]
    # paths:
    #   - '**.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Job

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run Lint
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    name: Test Job

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run Tests
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    name: Build Job
    needs: [lint, test]

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Build Application with Docker
        run: |
          docker build --tag=backend:latest .